name: 'Release to production'
description: 'Release to production'

env:
  MANIFEST_REPO: "voiapp/argo-cd-apps"
  MANIFEST_REPO_BRANCH: "main"
  YQ_VERSION: 3.4.1

inputs:
  github-pat:
    description: 'Github Personal Access Token. Used to create PR using GitHub API in another repository.'
    required: true

runs:
  using: "composite"

  steps:
    - name: Install yq
      shell: bash
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    - name: Update image with yq and push branch
      run: |
        TAG=$(basename ${GITHUB_REF})
        SHA=$(echo $GITHUB_SHA | cut -c 1-7)
        VALUES_FILE="${{ github.event.repository.name }}/values/prod.yaml"
        IMAGE=$(yq r ${VALUES_FILE} "image" | sed "s/:.*$//")":${TAG}-${SHA}"

        git config --global user.email ${GITHUB_ACTOR}@voiapp.io
        git config --global user.name ${GITHUB_ACTOR}
        git checkout -b deploy-prod-${{github.sha}}

        yq w ${VALUES_FILE} "image" ${IMAGE} > ${VALUES_FILE}

        git commit -am "Set image for deploy using tag ${TAG}-${SHA}. Commit: ${{github.event.head_commit.message}} by ${{github.event.head_commit.author.name}}"
        git push --set-upstream origin deploy-prod-${{github.sha}}
    - name: Create PR
      shell: bash
      run: |
        gh auth login --with-token <<< ${{ inputs.github-pat }}
        gh pr create -t "Deploy ${{ github.event.repository.name }} to production by ${{github.event.head_commit.author.name}}" \
        -b "Deploy new image to production for SHA ${{github.sha}}. Commit: ${{github.event.head_commit.message}} by ${{github.event.head_commit.author.name}}" \
        -B ${{env.MANIFEST_REPO_BRANCH}} -H deploy-prod-${{github.sha}}
