name: 'Release to staging'
description: 'Deploys to staging'

env:
  MANIFEST_REPO: "voiapp/argo-cd-apps"
  MANIFEST_REPO_BRANCH: "main"
  YQ_VERSION: 3.4.1

inputs:
  gcloud-service-account:
    description: 'Base64-encoded service account. Used to download private Docker images.'
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout code
      uses: actions/checkout@v2 #Migrate to raw bash or move to calling action
    - name: Create image
      shell: bash
      run: |
        echo "${{ inputs.gcloud-service-account }}" | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
        TAG_NAME=PR-${{ github.event.pull_request.number }} make push
    - name: Checkout manifests
      uses: actions/checkout@v2 #Migrate to raw bash or move to calling action
      with:
        repository: ${{ env.MANIFEST_REPO }}
        ref: ${{ env.MANIFEST_REPO_BRANCH }}
        ssh-key: ${{ secrets.ARGO_CD_APPS_TOKEN }}
    - name: Install yq
      shell: bash
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    - name: Update image with yq and push commit
      shell: bash
      run: |
        TAG=PR-${{ github.event.pull_request.number }}
        SHA=$(echo $GITHUB_SHA | cut -c 1-7)
        VALUES_FILE="${{ github.event.repository.name }}/values/stage.yaml"
        IMAGE=$(yq r ${VALUES_FILE} "image" | sed "s/:.*$//")":${TAG}-${SHA}"
        yq w ${VALUES_FILE} "image" ${IMAGE} > ${VALUES_FILE}

        git config --global user.email ${GITHUB_ACTOR}@voiapp.io
        git config --global user.name ${GITHUB_ACTOR}
        git commit -am "Set image for deploy"
        git push
