name: 'Release to production'
description: 'Deploys to production'

inputs:
  gcloud-service-account:
    description: 'Base64-encoded service account. Used to download private Docker images.'
    required: true

  spinnaker-secret:
    description: 'Secret used to call the webhook on Spinnaker.'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.gcloud-service-account }}" | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
      shell: bash

    - run: TAG_NAME=$(basename ${GITHUB_REF}) make push
      shell: bash
      env:
        DOCKER_TOOLS: true

    - run: TAG_NAME=$(basename ${GITHUB_REF}) make trigger_spinnaker
      shell: bash
      env:
        SPINNAKER_SECRET: ${{ inputs.spinnaker-secret }}
